[package]
name = "fetcher"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = {version = "0.12.11", features = ["zstd", "rustls-tls-manual-roots"]}
tokio = {version ="1.42.0", features = ["macros", "fs", "rt-multi-thread"]}
