[package]
name = "zcash_local_net"
version = "0.1.0"
edition = "2021"

[dependencies]
zcash_primitives = { git = "https://github.com/zingolabs/librustzcash.git", tag = "zcash_client_sqlite-0.11.2_plus_zingolabs_changes-1-g7ad60b5d5-2-g121371a08"  }
tempfile = "3.13.0"
